spring.application.name=backend

# SMTP settings
smtp.host=
smtp.port=587
smtp.username=
smtp.password=
smtp.from=
smtp.ssl=false
smtp.starttls=true
smtp.timeoutMs=10000

# JWT Configuration
jwt.secret=1f720aff49fcbb93bae9e17fe307640c2919177ab48148d6d211513adb6c2a7e
jwt.expiration-ms=3600000

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/fooddb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root_pass

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.show-actuator=false
springdoc.swagger-ui.use-root-path=true
springdoc.override-with-generic-response=false
